name: build-telegram-bot

on:
  push:
    branches-ignore:
      - master
      - main
    paths-ignore:
      - '**.md'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Runner Repository Downloads
        uses: actions/checkout@v2
      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build Application
        run: ./gradlew --no-daemon classes processResources compileKotlin compileJava