name: build-telegram-bot

on:
  push:
    paths-ignore:
      - '**.md'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TELEGRAM__RENT__BOT__TOKEN: ${{secrets.RENT_BOT_TOKEN}}
      TELEGRAM__RENT__CHANNELS: ${{secrets.RENT_CHANNELS}}
    steps:
      - name: Runner Repository Downloads
        uses: actions/checkout@v2
      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build Application
        run: ./gradlew --no-daemon classes processResources compileKotlin compileJava
