name: build-telegram-bot

on:
  push:
    branches-ignore:
      - master
      - main
    paths-ignore:
      - '**.md'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Runner Repository Downloads
        uses: actions/checkout@v2
      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build Application
        run: ./gradlew --no-daemon classes process processResources compileKotlin compileJava