name: deploy-telegram-bot

on:
  push:
    branches:
      - master
      - deploy
    paths-ignore:
      - '**.md'
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TELEGRAM__RENT__BOT__TOKEN: ${{secrets.RENT_BOT_TOKEN}}
      TELEGRAM__RENT__CHANNELS: ${{secrets.RENT_CHANNELS}}
    steps:
      - name: Runner Repository Downloads
        uses: actions/checkout@v2
      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build Fat Application Jar
        run: ./gradlew jar -Dtelegram.rent.bot.token=${{secrets.RENT_BOT_TOKEN}} -Dtelegram.rent.channels=${{secrets.RENT_CHANNELS}}
        env:
          TELEGRAM__RENT__BOT__TOKEN: ${{ secrets.RENT_BOT_TOKEN }}
          TELEGRAM__RENT__CHANNELS: ${{ secrets.RENT_CHANNELS }}
      - name: Copy single file to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: build/libs/telegram.rent.bot-1.0.jar
          remote: /home/jin/telegram-bot.jar
          host: ${{ secrets.HOST_BOT }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          rmRemote: true