name: reviewdog

on:
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest

    steps:
      - name: Runner Repository Downloads
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew detekt && cat build/reports/detekt/detekt.xml | reviewdog -f=checkstyle -name="linter" -reporter="github-pr-check" -level="error"